### PR TITLE
Fix/crud-UI

### PR DESCRIPTION
**Pull request by thqmos**
Modified the current CRUD operations to work with the reference data

### CODE REVIEW

**Review by xyclose11 — COMMENTED** [review]
### Tested functionality with pre-existing MongoDB database.

**Review by xyclose11 — COMMENTED** [review]
### Issue with "defaultvalue" prop in file "Form.tsx" 

Issue dealt with the defaultvalue prop being set on the <option> HTML tag.
`
<label htmlFor="type">Type</label>
        <select name="type" value={form.type} onChange={handleChange} required>
          <option value="" selected disabled hidden>Choose here</option>
          <option value="website">Website</option>
          <option value="book">Book</option>
          <option value="journal">Journal</option>
        </select>
`

**Comment by chrgarcia19** [comment]
Viewing issue. Having 2 books and clicking view for one of them deletes the other book.

**Comment by chrgarcia19** [comment]
Issue with an "Unhandled Runtime Error" when removing a contributor.

**Comment by chrgarcia19** [comment]
Issue with hitting the form's submit button causing a dialogue box appear saying "Failed to Add Reference"

**Pull request closed without merging**
